# Generated by Django 4.0.4 on 2023-07-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryitems',
            name='category',
        ),
        migrations.RemoveField(
            model_name='laundryitems',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='laundryitems',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='laundryitems',
            name='laundry_type',
        ),
        migrations.RemoveField(
            model_name='laundryitems',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='laundryproducts',
            name='laundry',
        ),
        migrations.RemoveField(
            model_name='laundryproducts',
            name='product',
        ),
        migrations.DeleteModel(
            name='Laundry',
        ),
        migrations.DeleteModel(
            name='LaundryItems',
        ),
        migrations.DeleteModel(
            name='LaundryProducts',
        ),
    ]
