# Generated by Django 4.0.4 on 2023-07-29 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0003_remove_laundryitems_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=250)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.FloatField(max_length=15)),
                ('tendered', models.FloatField(max_length=15)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'In-progress'), ('2', 'Done'), ('3', 'Picked Up')], default=0, max_length=2)),
                ('payment', models.CharField(choices=[('0', 'Unpaid'), ('1', 'Paid')], default=0, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('Coupon_code', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('1', 'Walkin'), ('2', 'Pickup')], default=1, max_length=2)),
                ('barcode', models.CharField(max_length=255)),
                ('franchise_details', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('pickup_time', models.CharField(choices=[('1', '9AM - 10AM'), ('2', '10AM - 11AM'), ('3', '11AM - 12PM'), ('4', '12PM - 1PM'), ('5', '1PM - 2PM'), ('6', '2PM - 3PM'), ('7', '3PM - 4PM'), ('8', '4PM - 5PM'), ('9', '5PM - 6PM'), ('10', '6PM - 7PM'), ('11', '7PM - 8PM'), ('12', '8PM - 9PM')], max_length=100)),
                ('delivery_time', models.CharField(choices=[('1', '9AM - 10AM'), ('2', '10AM - 11AM'), ('3', '11AM - 12PM'), ('4', '12PM - 1PM'), ('5', '1PM - 2PM'), ('6', '2PM - 3PM'), ('7', '3PM - 4PM'), ('8', '4PM - 5PM'), ('9', '5PM - 6PM'), ('10', '6PM - 7PM'), ('11', '7PM - 8PM'), ('12', '8PM - 9PM')], max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'List of Laundries',
            },
        ),
        migrations.CreateModel(
            name='LaundryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=15)),
                ('quantity', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('pincode', models.CharField(max_length=100)),
                ('feild_2', models.CharField(max_length=100)),
                ('feild_3', models.CharField(max_length=100)),
                ('feild_4', models.CharField(max_length=100)),
                ('feild_5', models.CharField(max_length=100)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_fk2', to='smile_dryApp.laundry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fk', to='smile_dryApp.products')),
            ],
            options={
                'verbose_name_plural': 'List of Laundry Products',
            },
        ),
        migrations.CreateModel(
            name='LaundryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=15)),
                ('weight', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fk', to='smile_dryApp.prices')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_type_fk', to='smile_dryApp.prices')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_fk', to='smile_dryApp.laundry')),
                ('laundry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_fk', to='smile_dryApp.prices')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_fk', to='smile_dryApp.prices')),
            ],
            options={
                'verbose_name_plural': 'List of Laundry Items',
            },
        ),
    ]
