# Generated by Django 4.0.4 on 2023-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0005_chatmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feild_2',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2),
        ),
    ]
