# Generated by Django 4.0.4 on 2023-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0006_remove_user_feild_2_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Franchise_name', models.CharField(max_length=100)),
                ('Live_stream_url', models.URLField()),
            ],
        ),
    ]
