# Generated by Django 4.0.4 on 2023-08-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0008_productpurchace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaundryProducts',
        ),
    ]
