# Generated by Django 4.0.4 on 2023-08-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0010_laundryproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryproducts',
            old_name='productpurchace',
            new_name='productpurchase',
        ),
    ]
