# Generated by Django 4.0.4 on 2023-08-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0011_rename_productpurchace_laundryproducts_productpurchase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productpurchace',
            new_name='Productpurchase',
        ),
    ]
