# Generated by Django 4.0.4 on 2023-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0013_rename_feild_2_products_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='GST',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_rate',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.FloatField(max_length=100),
        ),
    ]
