# Generated by Django 4.0.4 on 2023-08-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0016_productsfranchise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='GST',
            new_name='feild_1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='purchase_rate',
            new_name='feild_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sale_price',
        ),
    ]
