# Generated by Django 4.2.4 on 2023-08-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0019_productsfranchise_stockinfranchise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryproductsfranchise',
            old_name='product',
            new_name='productsfranchise',
        ),
        migrations.RenameField(
            model_name='stockinfranchise',
            old_name='product',
            new_name='productsfranchise',
        ),
    ]
