# Generated by Django 4.2.4 on 2023-08-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0020_rename_product_laundryproductsfranchise_productsfranchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='product',
        ),
        migrations.DeleteModel(
            name='LaundryProducts',
        ),
        migrations.DeleteModel(
            name='Productpurchase',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
    ]
