# Generated by Django 4.2.4 on 2023-08-08 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0022_productpurchase_products_stockin_laundryproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseLaundryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=15)),
                ('quantity', models.FloatField(default=0, max_length=15)),
                ('total_amount', models.FloatField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'List of Laundry Products',
            },
        ),
        migrations.CreateModel(
            name='FranchiseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0, max_length=15)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Products',
            },
        ),
        migrations.CreateModel(
            name='FranchiseStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('franchiseproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile_dryApp.franchiseproducts')),
            ],
            options={
                'verbose_name_plural': 'List of Stock-In',
            },
        ),
        migrations.RemoveField(
            model_name='stockinfranchise',
            name='productsfranchise',
        ),
        migrations.DeleteModel(
            name='LaundryProductsFranchise',
        ),
        migrations.DeleteModel(
            name='ProductsFranchise',
        ),
        migrations.DeleteModel(
            name='StockInFranchise',
        ),
        migrations.AddField(
            model_name='franchiselaundryproducts',
            name='franchiseproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchiseproduct_fk', to='smile_dryApp.franchiseproducts'),
        ),
    ]
