# Generated by Django 4.2.4 on 2023-08-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0023_franchiselaundryproducts_franchiseproducts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FranchiseLaundryProducts',
        ),
    ]
