# Generated by Django 4.2.4 on 2023-08-09 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0026_franchiseproducts_usedproducts_franchisestockin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseStockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('franchise_details', models.CharField(max_length=250)),
                ('feild_2', models.CharField(max_length=100)),
                ('feild_3', models.CharField(max_length=100)),
                ('feild_4', models.CharField(max_length=100)),
                ('feild_5', models.CharField(max_length=100)),
                ('franchiseproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smile_dryApp.franchiseproducts')),
            ],
            options={
                'verbose_name_plural': 'List of Stock-out',
            },
        ),
    ]
