# Generated by Django 4.2.4 on 2023-08-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0028_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('1', 'Percentage'), ('2', 'Fixed Amount'), ('3', 'Free Shipping')], default=1, max_length=2),
        ),
    ]
