# Generated by Django 4.2.4 on 2023-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0032_remove_products_feild_1_products_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='feild_2',
        ),
        migrations.AddField(
            model_name='prices',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Categories'),
        ),
    ]
