# Generated by Django 4.2.4 on 2023-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0034_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='banner_type',
            field=models.CharField(choices=[('Home Page Banner', 'Home Page Banner'), ('Offer Banner', 'Offer Banner'), ('Website Offer Banner', 'Website Offer Banner')], default=1, max_length=250),
        ),
    ]
