# Generated by Django 4.2.4 on 2023-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0035_alter_banners_banner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='feild_1',
        ),
        migrations.AddField(
            model_name='banners',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='banner_type',
            field=models.CharField(choices=[('Home Page Banner', 'Home Page Banner'), ('Offer Banner', 'Offer Banner'), ('Website Offer Banner', 'Website Offer Banner')], default='Home Page Banner', max_length=250),
        ),
    ]
