# Generated by Django 4.2.4 on 2023-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0036_remove_banners_feild_1_banners_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='feild_2',
            new_name='GST',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='feild_4',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='feild_5',
        ),
        migrations.AddField(
            model_name='products',
            name='purchase_rate',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
