# Generated by Django 4.2.4 on 2023-08-12 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0042_products_feild_2_products_feild_3_products_feild_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(max_length=250)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('alternative_phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('email_1', models.EmailField(max_length=250)),
                ('email_2', models.EmailField(max_length=250)),
                ('email_3', models.EmailField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Banners')),
                ('description', models.TextField(blank=True, null=True)),
                ('feild_2', models.CharField(max_length=100)),
                ('feild_3', models.CharField(max_length=100)),
                ('feild_4', models.CharField(max_length=100)),
                ('feild_5', models.CharField(max_length=100)),
                ('feild_6', models.CharField(max_length=100)),
                ('feild_7', models.CharField(max_length=100)),
                ('feild_8', models.CharField(max_length=100)),
                ('feild_9', models.CharField(max_length=100)),
            ],
        ),
    ]
