# Generated by Django 4.2.4 on 2023-08-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0044_termscondition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsCondition',
        ),
    ]
