# Generated by Django 4.2.4 on 2023-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0047_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='vendor_details',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
