# Generated by Django 4.2.4 on 2023-08-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0053_franchise_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'In-progress'), ('2', 'Done'), ('3', 'Picked Up'), ('4', 'Canceled')], default=0, max_length=2),
        ),
    ]
