# Generated by Django 4.2.4 on 2023-08-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0057_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='feild_2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='feild_3',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='feild_4',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='feild_5',
        ),
    ]
