# Generated by Django 4.2.4 on 2023-08-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0058_remove_vendor_feild_2_remove_vendor_feild_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='franchise_city',
            new_name='city',
        ),
    ]
