# Generated by Django 4.2.4 on 2023-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0059_rename_franchise_city_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feild_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
