# Generated by Django 4.2.4 on 2023-08-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0060_user_feild_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='feild_3',
            new_name='franchise_details',
        ),
    ]
