# Generated by Django 4.2.4 on 2023-08-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0061_rename_feild_3_user_franchise_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
