# Generated by Django 4.2.4 on 2023-08-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0064_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='Rider_details'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='Rider_details'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Rider_details'),
        ),
    ]
