# Generated by Django 4.2.4 on 2023-08-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0065_user_aadhar_user_license_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryproducts',
            name='total_amount_cgst',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='laundryproducts',
            name='total_amount_wgst',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='total_amount_cgst',
            field=models.FloatField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='total_amount_wgst',
            field=models.FloatField(default=0, max_length=15),
        ),
    ]
