# Generated by Django 4.2.4 on 2023-08-24 07:26

from django.db import migrations, models
import smile_dryApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0067_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='alternative_phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[smile_dryApp.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[smile_dryApp.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[smile_dryApp.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[smile_dryApp.models.validate_phone]),
        ),
    ]
