# Generated by Django 4.2.4 on 2023-08-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0068_alter_contact_alternative_phone_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0, max_length=15)),
                ('discount_type', models.CharField(choices=[('1', 'Percentage'), ('2', 'Fixed Amount'), ('3', 'Free Shipping')], default=1, max_length=2)),
                ('total_amount', models.FloatField(max_length=15)),
                ('total_amount_wgst', models.FloatField(default=0, max_length=15)),
                ('total_amount_cgst', models.FloatField(default=0, max_length=15)),
                ('pincode', models.CharField(max_length=100)),
                ('feild_2', models.CharField(max_length=100)),
                ('feild_3', models.CharField(max_length=100)),
                ('feild_4', models.CharField(max_length=100)),
                ('feild_5', models.CharField(max_length=100)),
                ('feild_6', models.CharField(max_length=100)),
                ('feild_7', models.CharField(max_length=100)),
                ('feild_8', models.CharField(max_length=100)),
                ('feild_9', models.CharField(max_length=100)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_fk', to='smile_dryApp.coupon')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_fk2', to='smile_dryApp.laundry')),
            ],
            options={
                'verbose_name_plural': 'List of Laundry Products',
            },
        ),
    ]
