# Generated by Django 4.2.4 on 2023-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0069_laundrycoupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='discount',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
