# Generated by Django 4.2.4 on 2023-08-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0070_laundry_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='discount',
        ),
    ]
