# Generated by Django 4.2.4 on 2023-08-31 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0071_remove_laundry_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
