# Generated by Django 4.2.4 on 2023-09-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0074_rename_franchise_name_coupon_franchise_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchiseproducts',
            options={},
        ),
    ]
