# Generated by Django 4.2.4 on 2023-09-04 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0077_alter_staffs_franchise_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpurchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
