# Generated by Django 4.2.4 on 2023-09-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0078_alter_productpurchase_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='client',
            field=models.CharField(max_length=250),
        ),
    ]
