# Generated by Django 4.2.4 on 2023-09-04 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0079_alter_productpurchase_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='franchise_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
