# Generated by Django 4.2.4 on 2023-09-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0085_alter_productpurchase_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='Franchise_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
