# Generated by Django 4.2.4 on 2023-09-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smile_dryApp', '0092_alter_franchisestockin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisestockout',
            name='franchise_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stokckout_franchise', to=settings.AUTH_USER_MODEL),
        ),
    ]
